name: Render Rmd to HTML
on:
  push:
    paths:
      - 'Vignette.Rmd'
jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
      - name: Setup pandoc
        uses: r-lib/actions/setup-pandoc@v2
      - name: Setup TinyTeX
        uses: r-lib/actions/setup-tinytex@v2
      - name: Install R and dependencies
        run: |
          sudo Rscript -e 'install.packages(c("knitr", "BiocManager"), repos="http://cran.rstudio.com/")' 
          sudo Rscript -e 'BiocManager::install("BiocStyle")'
          sudo Rscript -e 'install.packages("rmarkdown", repos="http://cran.rstudio.com/")'
      - name: Render Rmd to HTML
        run: |
          sudo Rscript -e "rmarkdown::render(input = 'Vignette.Rmd', BiocStyle::html_document())"
      - name: Commit and push changes
        run: |
          git add Vignette.html
          git commit -m "Render Vignette.Rmd to HTML"
          git push origin HEAD:main
